/**
 * Every icon in the game, named for what it means rather than what it looks like.
 * Font Awesome only — no emoji, which render differently on every platform.
 */
export {
  faBullhorn as iconCall,
  faMagnifyingGlass as iconHunt,
  faPuzzlePiece as iconPuzzle,
  faCircleCheck as iconFound,
  faCircleXmark as iconWrong,
  faTrophy as iconTrophy,
  faMedal as iconMedal,
  faClock as iconClock,
  faStopwatch as iconStopwatch,
  faUsers as iconPlayers,
  faCrown as iconHost,
  faRightFromBracket as iconLeave,
  faDoorOpen as iconWalkedOut,
  faPlay as iconStart,
  faRotateRight as iconReplay,
  faVolumeHigh as iconSoundOn,
  faVolumeXmark as iconSoundOff,
  faCopy as iconCopy,
  faPlugCircleXmark as iconOffline,
  faSliders as iconSettings,
  faHourglassHalf as iconHourglass,
  faUserClock as iconWaiting,
  faArrowsLeftRight as iconDrag,
  faLocationCrosshairs as iconPick,
  faTriangleExclamation as iconWarning,
  faCircleInfo as iconInfo,
  faHashtag as iconNumber,
  faBan as iconBlocked,
  faChevronRight as iconNext,
  faMagnifyingGlassPlus as iconZoomIn,
  faMagnifyingGlassMinus as iconZoomOut,
  faCompress as iconFit,
  faCheck as iconAccept,
  faXmark as iconClose,
  faLockOpen as iconRoomOpen,
  faGraduationCap as iconTeach,
  faHandPointer as iconHand,
  faRobot as iconBot,
  faEye as iconWatch,
  faUserPlus as iconJoin,
  faPlus as iconCreate,
  faArrowLeft as iconBack,
  faChevronDown as iconCollapse,
  faPause as iconPaused,
  faGear as iconGear,
  faPalette as iconTheme,
  faEllipsis as iconThinking,
} from '@fortawesome/free-solid-svg-icons';
